server:
  port: 8081
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 50468664243-7agc4k3k3t04bdrvm6i9ft40j8kjvo1m.apps.googleusercontent.com
            client-secret: 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
            scope: openid, profile, email
            redirect-uri: http://localhost:8081/login/oauth2/code/google

          naver:
            authorization-grant-type: authorization_code
            client-id: WxuDa3MVRtFAkEP23p8b
            client-secret: MnksYfpR3x
            client-name: naver
            redirect-uri: http://localhost:8081/login/oauth2/code/naver
            scope: name, email, profile_image

          kakao:
            authorization-grant-type: authorization_code
            client-id: f8112cd9f6802f96fb71c50eeee827c5
            client-secret: lSBMCoPruHYOFGaS8myskE56utdOIdJd
            client-name: kakao
            redirect-uri: http://localhost:8081/login/oauth2/code/kakao
#            scope: profile, email
            scope: openid, profile, email

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            issuer-uri: https://kauth.kakao.com
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v1/oidc/userinfo
            jwk-set-uri: https://kauth.kakao.com/.well-known/jwks.json
            user-name-attribute: id


logging:
  level:
    oauth2client.sociallogin: debug